# Generated by Django 3.2.4 on 2024-07-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flan',
            fields=[
                ('flan_id', models.AutoField(primary_key=True, serialize=False)),
                ('flan_name', models.CharField(max_length=64)),
                ('flan_description', models.TextField()),
                ('flan_image_url', models.URLField()),
                ('flan_slug', models.SlugField()),
                ('flan_is_private', models.BooleanField()),
            ],
        ),
    ]
