# Generated by Django 5.0.7 on 2024-07-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_contactform_contact_form_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="flan",
            name="flan_recipe",
            field=models.TextField(default="recipe here"),
        ),
    ]
